version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-maria}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-maria}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8082"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: maria
      ME_CONFIG_BASICAUTH_PASSWORD: maria!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: maria
      ME_CONFIG_MONGODB_ADMINPASSWORD: maria!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/mongodb
    networks:
      - mongo-compose-network

networks:
  postgres:
    driver: bridge
  mongo-compose-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongodb: